# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13etfkUlcWBkUIFw1GxUeyhuPn_K_2tt3
"""

import streamlit as st
import pandas as pd
import joblib
model=joblib.load('Salary_prediction_model .pkl')
encoders=joblib.load('label_encoder_sp.pkl')
st.title('Salary Prediction App')
age=st.number_input('Enter Age',18,65,25)
gender=st.selectbox(' Gender',encoders['Gender'].classes_)
education_level=st.selectbox('Education Level',encoders['Education Level'].classes_)
job=st.selectbox('Job Title',encoders['Job Title'].classes_)
experince=st.number_input(' Yours of Experience',0.0,40.0,2.0)
# Create Datafreame
df=pd.DataFrame({
    'age':[age],
    'Gender':[gender],
    'Education Level':[education_level],
    'Job Title':[job],
    'Years of Experience':[experince]
})
#Predict
if st.button('Predict salary'):
  for col in df.columns:
    df[col]=encoders[col].transform(df[col])

  prediction=model.predict(df)
  st.success(f"Predicted Salary:{prediction[0]:,.2f}")
